// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqQvaYh4GDCFR-CDPclHUMwbAd7SdIPA',
    appId: '1:377958126069:web:a437a4394b1f2945c3d0bc',
    messagingSenderId: '377958126069',
    projectId: 'proyectofinal-d8980',
    authDomain: 'proyectofinal-d8980.firebaseapp.com',
    storageBucket: 'proyectofinal-d8980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqWsikfQXiyKbpn30zVVB43_pJ6AM0nKc',
    appId: '1:377958126069:android:089ca4a8421204e0c3d0bc',
    messagingSenderId: '377958126069',
    projectId: 'proyectofinal-d8980',
    storageBucket: 'proyectofinal-d8980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMhmRF46mRmqh8A_V0i35aED5aOLIcMko',
    appId: '1:377958126069:ios:015863e34e9f5137c3d0bc',
    messagingSenderId: '377958126069',
    projectId: 'proyectofinal-d8980',
    storageBucket: 'proyectofinal-d8980.firebasestorage.app',
    iosClientId: '377958126069-767vqibtqoajsde0nbgnv9rpkml48i2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.jessicalopesc1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMhmRF46mRmqh8A_V0i35aED5aOLIcMko',
    appId: '1:377958126069:ios:015863e34e9f5137c3d0bc',
    messagingSenderId: '377958126069',
    projectId: 'proyectofinal-d8980',
    storageBucket: 'proyectofinal-d8980.firebasestorage.app',
    iosClientId: '377958126069-767vqibtqoajsde0nbgnv9rpkml48i2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.jessicalopesc1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDqQvaYh4GDCFR-CDPclHUMwbAd7SdIPA',
    appId: '1:377958126069:web:34baaa730d6e415ac3d0bc',
    messagingSenderId: '377958126069',
    projectId: 'proyectofinal-d8980',
    authDomain: 'proyectofinal-d8980.firebaseapp.com',
    storageBucket: 'proyectofinal-d8980.firebasestorage.app',
  );
}
